# Generated by Django 5.2.8 on 2025-11-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_image_project_pinned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
